
export type Country = {
    value: string;
    label: string;
    phone: string;
    flag: string;
}

export const countries: Country[] = [
    { value: "AF", label: "Afghanistan", phone: "93", flag: "/flags/af.svg" },
    { value: "AL", label: "Albania", phone: "355", flag: "/flags/al.svg" },
    { value: "DZ", label: "Algeria", phone: "213", flag: "/flags/dz.svg" },
    { value: "AS", label: "American Samoa", phone: "1-684", flag: "/flags/as.svg" },
    { value: "AD", label: "Andorra", phone: "376", flag: "/flags/ad.svg" },
    { value: "AO", label: "Angola", phone: "244", flag: "/flags/ao.svg" },
    { value: "AI", label: "Anguilla", phone: "1-264", flag: "/flags/ai.svg" },
    { value: "AQ", label: "Antarctica", phone: "672", flag: "/flags/aq.svg" },
    { value: "AG", label: "Antigua and Barbuda", phone: "1-268", flag: "/flags/ag.svg" },
    { value: "AR", label: "Argentina", phone: "54", flag: "/flags/ar.svg" },
    { value: "AM", label: "Armenia", phone: "374", flag: "/flags/am.svg" },
    { value: "AW", label: "Aruba", phone: "297", flag: "/flags/aw.svg" },
    { value: "AU", label: "Australia", phone: "61", flag: "/flags/au.svg" },
    { value: "AT", label: "Austria", phone: "43", flag: "/flags/at.svg" },
    { value: "AZ", label: "Azerbaijan", phone: "994", flag: "/flags/az.svg" },
    { value: "BS", label: "Bahamas", phone: "1-242", flag: "/flags/bs.svg" },
    { value: "BH", label: "Bahrain", phone: "973", flag: "/flags/bh.svg" },
    { value: "BD", label: "Bangladesh", phone: "880", flag: "/flags/bd.svg" },
    { value: "BB", label: "Barbados", phone: "1-246", flag: "/flags/bb.svg" },
    { value: "BY", label: "Belarus", phone: "375", flag: "/flags/by.svg" },
    { value: "BE", label: "Belgium", phone: "32", flag: "/flags/be.svg" },
    { value: "BZ", label: "Belize", phone: "501", flag: "/flags/bz.svg" },
    { value: "BJ", label: "Benin", phone: "229", flag: "/flags/bj.svg" },
    { value: "BM", label: "Bermuda", phone: "1-441", flag: "/flags/bm.svg" },
    { value: "BT", label: "Bhutan", phone: "975", flag: "/flags/bt.svg" },
    { value: "BO", label: "Bolivia", phone: "591", flag: "/flags/bo.svg" },
    { value: "BA", label: "Bosnia and Herzegovina", phone: "387", flag: "/flags/ba.svg" },
    { value: "BW", label: "Botswana", phone: "267", flag: "/flags/bw.svg" },
    { value: "BR", label: "Brazil", phone: "55", flag: "/flags/br.svg" },
    { value: "IO", label: "British Indian Ocean Territory", phone: "246", flag: "/flags/io.svg" },
    { value: "VG", label: "British Virgin Islands", phone: "1-284", flag: "/flags/vg.svg" },
    { value: "BN", label: "Brunei", phone: "673", flag: "/flags/bn.svg" },
    { value: "BG", label: "Bulgaria", phone: "359", flag: "/flags/bg.svg" },
    { value: "BF", label: "Burkina Faso", phone: "226", flag: "/flags/bf.svg" },
    { value: "BI", label: "Burundi", phone: "257", flag: "/flags/bi.svg" },
    { value: "KH", label: "Cambodia", phone: "855", flag: "/flags/kh.svg" },
    { value: "CM", label: "Cameroon", phone: "237", flag: "/flags/cm.svg" },
    { value: "CA", label: "Canada", phone: "1", flag: "/flags/ca.svg" },
    { value: "CV", label: "Cape Verde", phone: "238", flag: "/flags/cv.svg" },
    { value: "KY", label: "Cayman Islands", phone: "1-345", flag: "/flags/ky.svg" },
    { value: "CF", label: "Central African Republic", phone: "236", flag: "/flags/cf.svg" },
    { value: "TD", label: "Chad", phone: "235", flag: "/flags/td.svg" },
    { value: "CL", label: "Chile", phone: "56", flag: "/flags/cl.svg" },
    { value: "CN", label: "China", phone: "86", flag: "/flags/cn.svg" },
    { value: "CX", label: "Christmas Island", phone: "61", flag: "/flags/cx.svg" },
    { value: "CC", label: "Cocos Islands", phone: "61", flag: "/flags/cc.svg" },
    { value: "CO", label: "Colombia", phone: "57", flag: "/flags/co.svg" },
    { value: "KM", label: "Comoros", phone: "269", flag: "/flags/km.svg" },
    { value: "CK", label: "Cook Islands", phone: "682", flag: "/flags/ck.svg" },
    { value: "CR", label: "Costa Rica", phone: "506", flag: "/flags/cr.svg" },
    { value: "HR", label: "Croatia", phone: "385", flag: "/flags/hr.svg" },
    { value: "CU", label: "Cuba", phone: "53", flag: "/flags/cu.svg" },
    { value: "CW", label: "Curacao", phone: "599", flag: "/flags/cw.svg" },
    { value: "CY", label: "Cyprus", phone: "357", flag: "/flags/cy.svg" },
    { value: "CZ", label: "Czech Republic", phone: "420", flag: "/flags/cz.svg" },
    { value: "CD", label: "Democratic Republic of the Congo", phone: "243", flag: "/flags/cd.svg" },
    { value: "DK", label: "Denmark", phone: "45", flag: "/flags/dk.svg" },
    { value: "DJ", label: "Djibouti", phone: "253", flag: "/flags/dj.svg" },
    { value: "DM", label: "Dominica", phone: "1-767", flag: "/flags/dm.svg" },
    { value: "DO", label: "Dominican Republic", phone: "1-809, 1-829, 1-849", flag: "/flags/do.svg" },
    { value: "TL", label: "East Timor", phone: "670", flag: "/flags/tl.svg" },
    { value: "EC", label: "Ecuador", phone: "593", flag: "/flags/ec.svg" },
    { value: "EG", label: "Egypt", phone: "20", flag: "/flags/eg.svg" },
    { value: "SV", label: "El Salvador", phone: "503", flag: "/flags/sv.svg" },
    { value: "GQ", label: "Equatorial Guinea", phone: "240", flag: "/flags/gq.svg" },
    { value: "ER", label: "Eritrea", phone: "291", flag: "/flags/er.svg" },
    { value: "EE", label: "Estonia", phone: "372", flag: "/flags/ee.svg" },
    { value: "ET", label: "Ethiopia", phone: "251", flag: "/flags/et.svg" },
    { value: "FK", label: "Falkland Islands", phone: "500", flag: "/flags/fk.svg" },
    { value: "FO", label: "Faroe Islands", phone: "298", flag: "/flags/fo.svg" },
    { value: "FJ", label: "Fiji", phone: "679", flag: "/flags/fj.svg" },
    { value: "FI", label: "Finland", phone: "358", flag: "/flags/fi.svg" },
    { value: "FR", label: "France", phone: "33", flag: "/flags/fr.svg" },
    { value: "PF", label: "French Polynesia", phone: "689", flag: "/flags/pf.svg" },
    { value: "GA", label: "Gabon", phone: "241", flag: "/flags/ga.svg" },
    { value: "GM", label: "Gambia", phone: "220", flag: "/flags/gm.svg" },
    { value: "GE", label: "Georgia", phone: "995", flag: "/flags/ge.svg" },
    { value: "DE", label: "Germany", phone: "49", flag: "/flags/de.svg" },
    { value: "GH", label: "Ghana", phone: "233", flag: "/flags/gh.svg" },
    { value: "GI", label: "Gibraltar", phone: "350", flag: "/flags/gi.svg" },
    { value: "GR", label: "Greece", phone: "30", flag: "/flags/gr.svg" },
    { value: "GL", label: "Greenland", phone: "299", flag: "/flags/gl.svg" },
    { value: "GD", label: "Grenada", phone: "1-473", flag: "/flags/gd.svg" },
    { value: "GU", label: "Guam", phone: "1-671", flag: "/flags/gu.svg" },
    { value: "GT", label: "Guatemala", phone: "502", flag: "/flags/gt.svg" },
    { value: "GG", label: "Guernsey", phone: "44-1481", flag: "/flags/gg.svg" },
    { value: "GN", label: "Guinea", phone: "224", flag: "/flags/gn.svg" },
    { value: "GW", label: "Guinea-Bissau", phone: "245", flag: "/flags/gw.svg" },
    { value: "GY", label: "Guyana", phone: "592", flag: "/flags/gy.svg" },
    { value: "HT", label: "Haiti", phone: "509", flag: "/flags/ht.svg" },
    { value: "HN", label: "Honduras", phone: "504", flag: "/flags/hn.svg" },
    { value: "HK", label: "Hong Kong", phone: "852", flag: "/flags/hk.svg" },
    { value: "HU", label: "Hungary", phone: "36", flag: "/flags/hu.svg" },
    { value: "IS", label: "Iceland", phone: "354", flag: "/flags/is.svg" },
    { value: "IN", label: "India", phone: "91", flag: "/flags/in.svg" },
    { value: "ID", label: "Indonesia", phone: "62", flag: "/flags/id.svg" },
    { value: "IR", label: "Iran", phone: "98", flag: "/flags/ir.svg" },
    { value: "IQ", label: "Iraq", phone: "964", flag: "/flags/iq.svg" },
    { value: "IE", label: "Ireland", phone: "353", flag: "/flags/ie.svg" },
    { value: "IM", label: "Isle of Man", phone: "44-1624", flag: "/flags/im.svg" },
    { value: "IL", label: "Israel", phone: "972", flag: "/flags/il.svg" },
    { value: "IT", label: "Italy", phone: "39", flag: "/flags/it.svg" },
    { value: "CI", label: "Ivory Coast", phone: "225", flag: "/flags/ci.svg" },
    { value: "JM", label: "Jamaica", phone: "1-876", flag: "/flags/jm.svg" },
    { value: "JP", label: "Japan", phone: "81", flag: "/flags/jp.svg" },
    { value: "JE", label: "Jersey", phone: "44-1534", flag: "/flags/je.svg" },
    { value: "JO", label: "Jordan", phone: "962", flag: "/flags/jo.svg" },
    { value: "KZ", label: "Kazakhstan", phone: "7", flag: "/flags/kz.svg" },
    { value: "KE", label: "Kenya", phone: "254", flag: "/flags/ke.svg" },
    { value: "KI", label: "Kiribati", phone: "686", flag: "/flags/ki.svg" },
    { value: "XK", label: "Kosovo", phone: "383", flag: "/flags/xk.svg" },
    { value: "KW", label: "Kuwait", phone: "965", flag: "/flags/kw.svg" },
    { value: "KG", label: "Kyrgyzstan", phone: "996", flag: "/flags/kg.svg" },
    { value: "LA", label: "Laos", phone: "856", flag: "/flags/la.svg" },
    { value: "LV", label: "Latvia", phone: "371", flag: "/flags/lv.svg" },
    { value: "LB", label: "Lebanon", phone: "961", flag: "/flags/lb.svg" },
    { value: "LS", label: "Lesotho", phone: "266", flag: "/flags/ls.svg" },
    { value: "LR", label: "Liberia", phone: "231", flag: "/flags/lr.svg" },
    { value: "LY", label: "Libya", phone: "218", flag: "/flags/ly.svg" },
    { value: "LI", label: "Liechtenstein", phone: "423", flag: "/flags/li.svg" },
    { value: "LT", label: "Lithuania", phone: "370", flag: "/flags/lt.svg" },
    { value: "LU", label: "Luxembourg", phone: "352", flag: "/flags/lu.svg" },
    { value: "MO", label: "Macau", phone: "853", flag: "/flags/mo.svg" },
    { value: "MK", label: "Macedonia", phone: "389", flag: "/flags/mk.svg" },
    { value: "MG", label: "Madagascar", phone: "261", flag: "/flags/mg.svg" },
    { value: "MW", label: "Malawi", phone: "265", flag: "/flags/mw.svg" },
    { value: "MY", label: "Malaysia", phone: "60", flag: "/flags/my.svg" },
    { value: "MV", label: "Maldives", phone: "960", flag: "/flags/mv.svg" },
    { value: "ML", label: "Mali", phone: "223", flag: "/flags/ml.svg" },
    { value: "MT", label: "Malta", phone: "356", flag: "/flags/mt.svg" },
    { value: "MH", label: "Marshall Islands", phone: "692", flag: "/flags/mh.svg" },
    { value: "MR", label: "Mauritania", phone: "222", flag: "/flags/mr.svg" },
    { value: "MU", label: "Mauritius", phone: "230", flag: "/flags/mu.svg" },
    { value: "YT", label: "Mayotte", phone: "262", flag: "/flags/yt.svg" },
    { value: "MX", label: "Mexico", phone: "52", flag: "/flags/mx.svg" },
    { value: "FM", label: "Micronesia", phone: "691", flag: "/flags/fm.svg" },
    { value: "MD", label: "Moldova", phone: "373", flag: "/flags/md.svg" },
    { value: "MC", label: "Monaco", phone: "377", flag: "/flags/mc.svg" },
    { value: "MN", label: "Mongolia", phone: "976", flag: "/flags/mn.svg" },
    { value: "ME", label: "Montenegro", phone: "382", flag: "/flags/me.svg" },
    { value: "MS", label: "Montserrat", phone: "1-664", flag: "/flags/ms.svg" },
    { value: "MA", label: "Morocco", phone: "212", flag: "/flags/ma.svg" },
    { value: "MZ", label: "Mozambique", phone: "258", flag: "/flags/mz.svg" },
    { value: "MM", label: "Myanmar", phone: "95", flag: "/flags/mm.svg" },
    { value: "NA", label: "Namibia", phone: "264", flag: "/flags/na.svg" },
    { value: "NR", label: "Nauru", phone: "674", flag: "/flags/nr.svg" },
    { value: "NP", label: "Nepal", phone: "977", flag: "/flags/np.svg" },
    { value: "NL", label: "Netherlands", phone: "31", flag: "/flags/nl.svg" },
    { value: "AN", label: "Netherlands Antilles", phone: "599", flag: "/flags/an.svg" },
    { value: "NC", label: "New Caledonia", phone: "687", flag: "/flags/nc.svg" },
    { value: "NZ", label: "New Zealand", phone: "64", flag: "/flags/nz.svg" },
    { value: "NI", label: "Nicaragua", phone: "505", flag: "/flags/ni.svg" },
    { value: "NE", label: "Niger", phone: "227", flag: "/flags/ne.svg" },
    { value: "NG", label: "Nigeria", phone: "234", flag: "/flags/ng.svg" },
    { value: "NU", label: "Niue", phone: "683", flag: "/flags/nu.svg" },
    { value: "KP", label: "North Korea", phone: "850", flag: "/flags/kp.svg" },
    { value: "MP", label: "Northern Mariana Islands", phone: "1-670", flag: "/flags/mp.svg" },
    { value: "NO", label: "Norway", phone: "47", flag: "/flags/no.svg" },
    { value: "OM", label: "Oman", phone: "968", flag: "/flags/om.svg" },
    { value: "PK", label: "Pakistan", phone: "92", flag: "/flags/pk.svg" },
    { value: "PW", label: "Palau", phone: "680", flag: "/flags/pw.svg" },
    { value: "PS", label: "Palestine", phone: "970", flag: "/flags/ps.svg" },
    { value: "PA", label: "Panama", phone: "507", flag: "/flags/pa.svg" },
    { value: "PG", label: "Papua New Guinea", phone: "675", flag: "/flags/pg.svg" },
    { value: "PY", label: "Paraguay", phone: "595", flag: "/flags/py.svg" },
    { value: "PE", label: "Peru", phone: "51", flag: "/flags/pe.svg" },
    { value: "PH", label: "Philippines", phone: "63", flag: "/flags/ph.svg" },
    { value: "PN", label: "Pitcairn", phone: "64", flag: "/flags/pn.svg" },
    { value: "PL", label: "Poland", phone: "48", flag: "/flags/pl.svg" },
    { value: "PT", label: "Portugal", phone: "351", flag: "/flags/pt.svg" },
    { value: "PR", label: "Puerto Rico", phone: "1-787, 1-939", flag: "/flags/pr.svg" },
    { value: "QA", label: "Qatar", phone: "974", flag: "/flags/qa.svg" },
    { value: "CG", label: "Republic of the Congo", phone: "242", flag: "/flags/cg.svg" },
    { value: "RE", label: "Reunion", phone: "262", flag: "/flags/re.svg" },
    { value: "RO", label: "Romania", phone: "40", flag: "/flags/ro.svg" },
    { value: "RU", label: "Russia", phone: "7", flag: "/flags/ru.svg" },
    { value: "RW", label: "Rwanda", phone: "250", flag: "/flags/rw.svg" },
    { value: "BL", label: "Saint Barthelemy", phone: "590", flag: "/flags/bl.svg" },
    { value: "SH", label: "Saint Helena", phone: "290", flag: "/flags/sh.svg" },
    { value: "KN", label: "Saint Kitts and Nevis", phone: "1-869", flag: "/flags/kn.svg" },
    { value: "LC", label: "Saint Lucia", phone: "1-758", flag: "/flags/lc.svg" },
    { value: "MF", label: "Saint Martin", phone: "590", flag: "/flags/mf.svg" },
    { value: "PM", label: "Saint Pierre and Miquelon", phone: "508", flag: "/flags/pm.svg" },
    { value: "VC", label: "Saint Vincent and the Grenadines", phone: "1-784", flag: "/flags/vc.svg" },
    { value: "WS", label: "Samoa", phone: "685", flag: "/flags/ws.svg" },
    { value: "SM", label: "San Marino", phone: "378", flag: "/flags/sm.svg" },
    { value: "ST", label: "Sao Tome and Principe", phone: "239", flag: "/flags/st.svg" },
    { value: "SA", label: "Saudi Arabia", phone: "966", flag: "/flags/sa.svg" },
    { value: "SN", label: "Senegal", phone: "221", flag: "/flags/sn.svg" },
    { value: "RS", label: "Serbia", phone: "381", flag: "/flags/rs.svg" },
    { value: "SC", label: "Seychelles", phone: "248", flag: "/flags/sc.svg" },
    { value: "SL", label: "Sierra Leone", phone: "232", flag: "/flags/sl.svg" },
    { value: "SG", label: "Singapore", phone: "65", flag: "/flags/sg.svg" },
    { value: "SX", label: "Sint Maarten", phone: "1-721", flag: "/flags/sx.svg" },
    { value: "SK", label: "Slovakia", phone: "421", flag: "/flags/sk.svg" },
    { value: "SI", label: "Slovenia", phone: "386", flag: "/flags/si.svg" },
    { value: "SB", label: "Solomon Islands", phone: "677", flag: "/flags/sb.svg" },
    { value: "SO", label: "Somalia", phone: "252", flag: "/flags/so.svg" },
    { value: "ZA", label: "South Africa", phone: "27", flag: "/flags/za.svg" },
    { value: "KR", label: "South Korea", phone: "82", flag: "/flags/kr.svg" },
    { value: "SS", label: "South Sudan", phone: "211", flag: "/flags/ss.svg" },
    { value: "ES", label: "Spain", phone: "34", flag: "/flags/es.svg" },
    { value: "LK", label: "Sri Lanka", phone: "94", flag: "/flags/lk.svg" },
    { value: "SD", label: "Sudan", phone: "249", flag: "/flags/sd.svg" },
    { value: "SR", label: "Suriname", phone: "597", flag: "/flags/sr.svg" },
    { value: "SJ", label: "Svalbard and Jan Mayen", phone: "47", flag: "/flags/sj.svg" },
    { value: "SZ", label: "Swaziland", phone: "268", flag: "/flags/sz.svg" },
    { value: "SE", label: "Sweden", phone: "46", flag: "/flags/se.svg" },
    { value: "CH", label: "Switzerland", phone: "41", flag: "/flags/ch.svg" },
    { value: "SY", label: "Syria", phone: "963", flag: "/flags/sy.svg" },
    { value: "TW", label: "Taiwan", phone: "886", flag: "/flags/tw.svg" },
    { value: "TJ", label: "Tajikistan", phone: "992", flag: "/flags/tj.svg" },
    { value: "TZ", label: "Tanzania", phone: "255", flag: "/flags/tz.svg" },
    { value: "TH", label: "Thailand", phone: "66", flag: "/flags/th.svg" },
    { value: "TG", label: "Togo", phone: "228", flag: "/flags/tg.svg" },
    { value: "TK", label: "Tokelau", phone: "690", flag: "/flags/tk.svg" },
    { value: "TO", label: "Tonga", phone: "676", flag: "/flags/to.svg" },
    { value: "TT", label: "Trinidad and Tobago", phone: "1-868", flag: "/flags/tt.svg" },
    { value: "TN", label: "Tunisia", phone: "216", flag: "/flags/tn.svg" },
    { value: "TR", label: "Turkey", phone: "90", flag: "/flags/tr.svg" },
    { value: "TM", label: "Turkmenistan", phone: "993", flag: "/flags/tm.svg" },
    { value: "TC", label: "Turks and Caicos Islands", phone: "1-649", flag: "/flags/tc.svg" },
    { value: "TV", label: "Tuvalu", phone: "688", flag: "/flags/tv.svg" },
    { value: "VI", label: "U.S. Virgin Islands", phone: "1-340", flag: "/flags/vi.svg" },
    { value: "UG", label: "Uganda", phone: "256", flag: "/flags/ug.svg" },
    { value: "UA", label: "Ukraine", phone: "380", flag: "/flags/ua.svg" },
    { value: "AE", label: "United Arab Emirates", phone: "971", flag: "/flags/ae.svg" },
    { value: "GB", label: "United Kingdom", phone: "44", flag: "/flags/gb.svg" },
    { value: "US", label: "United States", phone: "1", flag: "/flags/us.svg" },
    { value: "UY", label: "Uruguay", phone: "598", flag: "/flags/uy.svg" },
    { value: "UZ", label: "Uzbekistan", phone: "998", flag: "/flags/uz.svg" },
    { value: "VU", label: "Vanuatu", phone: "678", flag: "/flags/vu.svg" },
    { value: "VA", label: "Vatican", phone: "379", flag: "/flags/va.svg" },
    { value: "VE", label: "Venezuela", phone: "58", flag: "/flags/ve.svg" },
    { value: "VN", label: "Vietnam", phone: "84", flag: "/flags/vn.svg" },
    { value: "WF", label: "Wallis and Futuna", phone: "681", flag: "/flags/wf.svg" },
    { value: "EH", label: "Western Sahara", phone: "212", flag: "/flags/eh.svg" },
    { value: "YE", label: "Yemen", phone: "967", flag: "/flags/ye.svg" },
    { value: "ZM", label: "Zambia", phone: "260", flag: "/flags/zm.svg" },
    { value: "ZW", label: "Zimbabwe", phone: "263", flag: "/flags/zw.svg" }
];

    